backend:
  name: github
  repo: stalgiag/class-work
  branch: main
  
media_folder: static/img
public_folder: /img

collections:
  - name: 'class'
    label: 'Class'
    folder: 'content/classes'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "markdown" }
      - { label: 'Image', name: 'thumbnail', widget: 'image'}
      - { label: "Alt Text", name: "alt", widget: "string" }
  - name: 'project'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: 'Image', name: 'thumbnail', widget: 'image'}
      - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - {
        label: 'Class',
        name: 'class',
        widget: 'relation',
        collection: 'class',
        search_fields: ['title'],
        value_field: 'title'
      }